p8105_hw2_zz2780
================
Lydia Zhang
2022-10-01

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

Problem 1

Import data

``` r
data1<-read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
                col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>% 
  janitor::clean_names() %>% 
  select(
    line, station_name, station_latitude, station_longitude, 
    starts_with("route"), entry, exit_only, vending, entrance_type, 
    ada) %>% 
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

The data is not tidy. I imported the data, selected variables of
interest, and converted entry variable from character to logic. The data
set origianlly has 1868 rows (observations) and 20 variables(columns).
Route number should be a variable and the values should be another
variable. We need to pivot the two variables from wider to longer
format.

How many distinct stations are there?

``` r
data1 %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

There are 84 distinct stations.

How many stations are ADA compliant?

``` r
data1 %>% 
  filter(ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 84 × 2
    ##    station_name                   line           
    ##    <chr>                          <chr>          
    ##  1 Atlantic Av-Barclays Ctr       4 Avenue       
    ##  2 DeKalb Av                      4 Avenue       
    ##  3 Pacific St                     4 Avenue       
    ##  4 Grand Central                  42nd St Shuttle
    ##  5 34th St                        6 Avenue       
    ##  6 47-50th Sts Rockefeller Center 6 Avenue       
    ##  7 Church Av                      6 Avenue       
    ##  8 21st St                        63rd Street    
    ##  9 Lexington Av                   63rd Street    
    ## 10 Roosevelt Island               63rd Street    
    ## # … with 74 more rows

84 stations are ADA compliant.

What proportion of station entrances / exits without vending allow
entrance?

``` r
data1 %>% 
  filter(vending == "NO") %>% 
  pull(entry) %>% 
  mean
```

    ## [1] 0.3770492

37.7% of the station entrances/exists are without vending allow
entrance.

Reformat data so that route number and route name are distinct
variables. How many distinct stations serve the A train? Of the stations
that serve the A train, how many are ADA compliant?

``` r
data1 %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A") %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 60 × 2
    ##    station_name                  line           
    ##    <chr>                         <chr>          
    ##  1 Times Square                  42nd St Shuttle
    ##  2 125th St                      8 Avenue       
    ##  3 145th St                      8 Avenue       
    ##  4 14th St                       8 Avenue       
    ##  5 168th St - Washington Heights 8 Avenue       
    ##  6 175th St                      8 Avenue       
    ##  7 181st St                      8 Avenue       
    ##  8 190th St                      8 Avenue       
    ##  9 34th St                       8 Avenue       
    ## 10 42nd St                       8 Avenue       
    ## # … with 50 more rows

``` r
data1 %>% 
  pivot_longer(
    route1:route11,
    names_to = "route_num",
    values_to = "route") %>% 
  filter(route == "A", ada == TRUE) %>% 
  select(station_name, line) %>% 
  distinct
```

    ## # A tibble: 17 × 2
    ##    station_name                  line            
    ##    <chr>                         <chr>           
    ##  1 14th St                       8 Avenue        
    ##  2 168th St - Washington Heights 8 Avenue        
    ##  3 175th St                      8 Avenue        
    ##  4 34th St                       8 Avenue        
    ##  5 42nd St                       8 Avenue        
    ##  6 59th St                       8 Avenue        
    ##  7 Inwood - 207th St             8 Avenue        
    ##  8 West 4th St                   8 Avenue        
    ##  9 World Trade Center            8 Avenue        
    ## 10 Times Square-42nd St          Broadway        
    ## 11 59th St-Columbus Circle       Broadway-7th Ave
    ## 12 Times Square                  Broadway-7th Ave
    ## 13 8th Av                        Canarsie        
    ## 14 Franklin Av                   Franklin        
    ## 15 Euclid Av                     Fulton          
    ## 16 Franklin Av                   Fulton          
    ## 17 Howard Beach                  Rockaway

60 distinct stations serve A train. And of those 17 are ADA compliant.

Problem 2

``` r
library(readxl)
```

Tidy Mr.Trash Wheel

``` r
data2=read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet="Mr. Trash Wheel", range="A2:N535")%>%
    janitor::clean_names() %>% 
  na.omit()
data2$sports_balls<-as.integer(data2$sports_balls)
data2$dumpster<-as.numeric(data2$dumpster)
```

Tidy Professor Trash Wheel

``` r
data2_1=read_excel("data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", sheet="Professor Trash Wheel", range="A2:N117")%>%
    janitor::clean_names() %>% 
  na.omit()
data2_1$sports_balls<-as.integer(data2_1$sports_balls)
```

Combine two data sets

``` r
data2$type<-"Mr. Trash Wheel"
data2<-data2%>%relocate(type, .after=dumpster)
data2_1$type<-"Professor Trash Wheel"
data2_1<-data2_1%>%relocate(type, .after=dumpster)
data2_tidy=
  bind_rows(data2, data2_1)%>%
  janitor::clean_names() %>%
  arrange(dumpster,type)
```

The resulting data set contains 524 observations and 15 variables. Type
indicates which trash wheel is used. The data set includes how many
weights (ton) and volume (cubic yard) each trash wheel collected on each
date at different dumpsters. And it records the number of different
types of trash that were picked up, as well as the number of homes it
can power.

What was the total weight of trash collected by Professor Trash Wheel?

``` r
data2_tidy%>%
  filter(type=="Professor Trash Wheel")%>%
  pull(weight_tons)%>%
sum
```

    ## [1] 135.5

The total weight of trash collected by Professor Trash Wheel was 135.5
tons.

What was the total number of sports balls collected by Mr. Trash Wheel
in 2020?

``` r
data2_tidy%>%
  filter(type=="Mr. Trash Wheel", year==2020)%>%
  pull(sports_balls)%>%
sum
```

    ## [1] 856

856 sports balls were collected by Mr. Trash Wheel in 2020.
